services:
  # --- HẠ TẦNG  ---
  mysql_auth:
    image: mysql:8.0
    container_name: mysql_auth
    cpus: "0.75"
    volumes:
      - ./data/mysql_auth:/var/lib/mysql  # Mount dữ liệu DB Auth ra ngoài
      - ./init/auth:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_AUTH_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_AUTH_DATABASE}
    ports: ["3307:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql_kho:
    image: mysql:8.0   
    container_name: mysql_inventory 
    cpus: "0.75"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql_kho:/var/lib/mysql # Mount dữ liệu DB Kho ra ngoài
      - ./init/inventory:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_KHO_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_KHO_DATABASE}
    ports: ["3308:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql_order:
    image: mysql:8.0
    container_name: mysql_order
    cpus: "0.75"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql_order:/var/lib/mysql # Mount dữ liệu DB Order ra ngoài
      - ./init/order:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ORDER_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_ORDER_DATABASE}
    ports: ["3309:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql_payment:
    image: mysql:8.0
    container_name: mysql_payment
    cpus: "0.75"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql_payment:/var/lib/mysql
      - ./init/payment:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PAYMENT_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_PAYMENT_DATABASE}
    ports: ["3310:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_kho:
    image: redis:7.2
    container_name: redis_inventory
    cpus: "0.25"
    volumes:
      - ./data/redis_kho:/data # Mount dữ liệu Redis ra ngoài
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    user: root
    cpus: "0.5"
    volumes:
      - ./data/zookeeper_data:/var/lib/zookeeper/data # Lưu trạng thái Zookeeper
      - ./data/zookeeper_log:/var/lib/zookeeper/log # Lưu log Zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    user: root
    cpus: "1.0"
    depends_on:
      - zookeeper
    volumes:
      - ./data/kafka_data:/var/lib/kafka/data # Lưu trữ các Topic và Message Kafka
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 5

  # --- DỊCH VỤ ---
  auth-service:
    image: microservices/auth-service:dev
    container_name: auth_service
    build:
      context: ./Auth_Service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql_auth:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${AUTH_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${AUTH_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_SPRING_DATASOURCE_PASSWORD}
      INVENTORY_BASE_URL: ${INVENTORY_BASE_URL}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: ${SPRING_KAFKA_PRODUCER_KEY_SERIALIZER}
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: ${SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER}
      APP_ADMIN_SUPPORT_EMAIL: ${APP_ADMIN_SUPPORT_EMAIL}
      JAVA_TOOL_OPTIONS: ${AUTH_JAVA_TOOL_OPTIONS}
    cpus: "1.0"

  notification-service:
    image: microservices/notification-service:dev
    container_name: notification_service
    build:
      context: ./Notification_Service
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      SPRING_KAFKA_CONSUMER_GROUP_ID: ${NOTIFICATION_KAFKA_CONSUMER_GROUP_ID}
      SPRING_KAFKA_LISTENER_CONCURRENCY: ${NOTIFICATION_KAFKA_LISTENER_CONCURRENCY}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
      JAVA_TOOL_OPTIONS: ${NOTIFICATION_JAVA_TOOL_OPTIONS}
    cpus: "0.5"

  inventory-service:
    image: microservices/inventory-service:dev
    container_name: inventory_service
    build:
      context: ./Inventory_Service
      dockerfile: Dockerfile
    ports:
      - "3002:8080"
    depends_on:
      mysql_kho:
        condition: service_healthy
      redis_kho:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${INVENTORY_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${INVENTORY_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${INVENTORY_SPRING_DATASOURCE_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
      JAVA_TOOL_OPTIONS: ${INVENTORY_JAVA_TOOL_OPTIONS}
    cpus: "1.0"

  order-service:
    image: microservices/order-service:dev
    container_name: order_service
    build:
      context: ./Order_Service
      dockerfile: Dockerfile
    ports:
      - "3003:8081"
    depends_on:
      mysql_order:
        condition: service_healthy
      inventory-service:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${ORDER_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${ORDER_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${ORDER_SPRING_DATASOURCE_PASSWORD}
      INVENTORY_BASE_URL: ${INVENTORY_BASE_URL}
      PAYMENT_BASE_URL: http://payment-service:8080
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      JAVA_TOOL_OPTIONS: ${ORDER_JAVA_TOOL_OPTIONS}
    cpus: "1.0"

  payment-service:
    image: microservices/payment-service:dev
    container_name: payment_service
    build:
      context: ./Payment_Service
      dockerfile: Dockerfile
    ports:
      - "3004:8082"
    depends_on:
      mysql_payment:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${PAYMENT_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${PAYMENT_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PAYMENT_SPRING_DATASOURCE_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      VNPAY_TMN_CODE: ${VNPAY_TMN_CODE}
      VNPAY_HASH_SECRET: ${VNPAY_HASH_SECRET}
      VNPAY_RETURN_URL: ${VNPAY_RETURN_URL}
      JAVA_TOOL_OPTIONS: ${PAYMENT_JAVA_TOOL_OPTIONS}
    cpus: "0.75"

  api-gateway:
    image: microservices/api-gateway:dev
    container_name: api_gateway
    build:
      context: ./Gateway_Service
      dockerfile: Dockerfile
    ports:
      - "3001:8085"
    depends_on:
      auth-service:
        condition: service_started
      inventory-service:
        condition: service_started
      order-service:
        condition: service_started
      payment-service:
        condition: service_started
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JAVA_TOOL_OPTIONS: ${GATEWAY_JAVA_TOOL_OPTIONS}
    cpus: "0.5"

  frontend:
    image: microservices/frontend:dev
    build:
      context: ./Frontend
      dockerfile: dockerfile
    container_name: frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      REACT_APP_API_GATEWAY_URL: http://localhost:3001
      REACT_APP_PAYMENT_SERVICE_URL: http://localhost:3004
    ports: ["3000:80"]
    depends_on:
      - api-gateway
    cpus: "0.25"

volumes:
  maven_repo:
